# Generated by Django 4.2.4 on 2023-08-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametype',
            name='label',
            field=models.CharField(max_length=75),
        ),
    ]
